// VEX V5 part weight database (grams).
// Sourced from amiheavy.keijay.me / Justin (675C) spreadsheet.

export interface VexPart {
  name: string;
  weight: number; // grams
  category: string;
}

export const VEX_CATEGORIES = [
  'Nuts',
  'Screws',
  'Standoffs',
  'Metal (per 1")',
  'Spacers',
  'Bearings',
  'Wheels',
  'Electronics',
  'Elements',
  'LS Gears',
  'HS Gears',
  '9P Sprockets',
  '6P Sprockets',
  '3P Sprockets',
  'Chains',
  'Sensors',
  'Pneumatics',
  'Misc.',
] as const;

export const VEX_PARTS: VexPart[] = [
  { name: 'Lock Nut', weight: 1.8, category: 'Nuts' },
  { name: 'Thin Lock Nut', weight: 1.3, category: 'Nuts' },
  { name: 'Keps Nut', weight: 1.3, category: 'Nuts' },
  { name: 'Hex Nut', weight: 0.4, category: 'Nuts' },
  { name: 'Piston Nut', weight: 0.9, category: 'Nuts' },
  { name: 'V2 L Piston Nut', weight: 1.6, category: 'Nuts' },
  { name: 'Nylon Hex Nut', weight: 0.1, category: 'Nuts' },
  { name: 'Nylon Nut', weight: 0.3, category: 'Nuts' },

  { name: 'Nylon Screw', weight: 0.1, category: 'Screws' },
  { name: '1/4" Screw', weight: 1.1, category: 'Screws' },
  { name: '3/8" Screw', weight: 1.3, category: 'Screws' },
  { name: '1/2" Screw', weight: 1.5, category: 'Screws' },
  { name: '5/8" Screw', weight: 1.8, category: 'Screws' },
  { name: '3/4" Screw', weight: 2, category: 'Screws' },
  { name: '7/8" Screw', weight: 2.3, category: 'Screws' },
  { name: '1" Screw', weight: 2.5, category: 'Screws' },
  { name: '1.25" Screw', weight: 3, category: 'Screws' },
  { name: '1.5" Screw', weight: 3.5, category: 'Screws' },
  { name: '1.75" Screw', weight: 4, category: 'Screws' },
  { name: '2" Screw', weight: 4.5, category: 'Screws' },
  { name: '2.25" Screw', weight: 5, category: 'Screws' },
  { name: '2.5" Screw', weight: 5.5, category: 'Screws' },

  { name: '1/4" Standoff', weight: 0.4, category: 'Standoffs' },
  { name: '1/2" Standoff', weight: 0.8, category: 'Standoffs' },
  { name: '3/4" Standoff', weight: 1.2, category: 'Standoffs' },
  { name: '7/8" Standoff', weight: 1.3, category: 'Standoffs' },
  { name: '1" Standoff', weight: 1.6, category: 'Standoffs' },
  { name: '1.5" Standoff', weight: 2.5, category: 'Standoffs' },
  { name: '2" Standoff', weight: 3.6, category: 'Standoffs' },
  { name: '3" Standoff', weight: 6, category: 'Standoffs' },
  { name: '4" Standoff', weight: 8.3, category: 'Standoffs' },
  { name: '5" Standoff', weight: 11.3, category: 'Standoffs' },

  { name: 'Alu 1x1 L', weight: 1.96, category: 'Metal (per 1")' },
  { name: 'Alu 2x2 L', weight: 3.91, category: 'Metal (per 1")' },
  { name: 'Alu 2x1 C', weight: 4.14, category: 'Metal (per 1")' },
  { name: 'Alu 3x1 C', weight: 5.54, category: 'Metal (per 1")' },
  { name: 'Alu 5x1 C', weight: 7.79, category: 'Metal (per 1")' },
  { name: 'Steel 5x Plate', weight: 12.06, category: 'Metal (per 1")' },
  { name: 'Steel 1x Plate', weight: 2.45, category: 'Metal (per 1")' },
  { name: 'Steel 2x1 C', weight: 7.7, category: 'Metal (per 1")' },
  { name: 'Channel Coupler', weight: 7.74, category: 'Metal (per 1")' },
  { name: 'Large Slide Rail', weight: 7.13, category: 'Metal (per 1")' },
  { name: 'Small Slide Rail', weight: 6.8, category: 'Metal (per 1")' },
  { name: 'LS Shaft', weight: 2, category: 'Metal (per 1")' },
  { name: 'HS Shaft', weight: 7.5, category: 'Metal (per 1")' },
  { name: 'Inner Slide', weight: 4.4, category: 'Metal (per 1")' },
  { name: 'Outer Slide', weight: 6.8, category: 'Metal (per 1")' },

  { name: '1/2" OD Spacer 1/8"', weight: 0.4, category: 'Spacers' },
  { name: '1/2" OD Spacer 1/4"', weight: 0.7, category: 'Spacers' },
  { name: '1/2" OD Spacer 3/8"', weight: 1.1, category: 'Spacers' },
  { name: '1/2" OD Spacer 1/2"', weight: 3.1, category: 'Spacers' },
  { name: '3/8" OD Spacer 1/8"', weight: 0.2, category: 'Spacers' },
  { name: '3/8" OD Spacer 1/4"', weight: 0.4, category: 'Spacers' },
  { name: '3/8" OD Spacer 3/8"', weight: 0.6, category: 'Spacers' },
  { name: '3/8" OD Spacer 1/2"', weight: 0.8, category: 'Spacers' },
  { name: '1/4" OD Spacer 1/8"', weight: 0.1, category: 'Spacers' },
  { name: '1/4" OD Spacer 1/4"', weight: 0.1, category: 'Spacers' },
  { name: '1/4" OD Spacer 3/8"', weight: 0.2, category: 'Spacers' },
  { name: 'Brass Insert', weight: 2.2, category: 'Spacers' },
  { name: 'Steel Insert', weight: 2.4, category: 'Spacers' },
  { name: 'Square Insert', weight: 1.4, category: 'Spacers' },
  { name: 'Circle Insert', weight: 0.2, category: 'Spacers' },
  { name: 'VersaHub', weight: 22.9, category: 'Spacers' },
  { name: '1/8" VersaHex', weight: 0.7, category: 'Spacers' },

  { name: 'LS Bearing 1x3', weight: 1.7, category: 'Bearings' },
  { name: 'LS Bearing 1x2', weight: 1.1, category: 'Bearings' },
  { name: 'LS Shaved 1x3', weight: 1.3, category: 'Bearings' },
  { name: 'LS Pillow 1x3', weight: 1.1, category: 'Bearings' },
  { name: 'LS Pillow 1x2', weight: 1.1, category: 'Bearings' },
  { name: 'Drilled LS Pillow', weight: 2.6, category: 'Bearings' },
  { name: 'HS Pillow 1x3', weight: 14.2, category: 'Bearings' },
  { name: 'HS Pillow 1x2', weight: 3.2, category: 'Bearings' },

  { name: '1.625" 30A Flex Wheel', weight: 12.6, category: 'Wheels' },
  { name: '1.625" 40A Flex Wheel', weight: 12.9, category: 'Wheels' },
  { name: '2" Omni Wheel', weight: 20.3, category: 'Wheels' },
  { name: '2.75" Omni Wheel', weight: 45.5, category: 'Wheels' },
  { name: '4" Omni Wheel', weight: 103.9, category: 'Wheels' },
  { name: '2.75" Wheel', weight: 50.4, category: 'Wheels' },

  { name: 'V5 Brain', weight: 291.7, category: 'Electronics' },
  { name: 'Radio', weight: 25.1, category: 'Electronics' },
  { name: 'Battery', weight: 247.6, category: 'Electronics' },
  { name: '11W Motor', weight: 145.4, category: 'Electronics' },
  { name: '5.5W Motor', weight: 90.9, category: 'Electronics' },
  { name: '330mm Cable', weight: 33, category: 'Electronics' },
  { name: 'Brain Cover', weight: 34.3, category: 'Electronics' },

  { name: 'Ring', weight: 122, category: 'Elements' },
  { name: 'Mogo', weight: 948, category: 'Elements' },
  { name: 'Cat', weight: 4722.91, category: 'Elements' },

  { name: '12T LS Gear', weight: 1.1, category: 'LS Gears' },
  { name: '36T LS Gear', weight: 5.5, category: 'LS Gears' },
  { name: '60T LS Gear', weight: 27.5, category: 'LS Gears' },

  { name: '12T HS Gear', weight: 6.9, category: 'HS Gears' },
  { name: '24T HS Gear', weight: 40, category: 'HS Gears' },
  { name: '36T HS Gear', weight: 17.4, category: 'HS Gears' },
  { name: '48T HS Gear', weight: 24, category: 'HS Gears' },
  { name: '60T HS Gear', weight: 31.3, category: 'HS Gears' },
  { name: '84T HS Gear', weight: 32, category: 'HS Gears' },

  { name: '6T 9P Sprocket', weight: 6.7, category: '9P Sprockets' },
  { name: '12T 9P Sprocket', weight: 12.6, category: '9P Sprockets' },
  { name: '18T 9P Sprocket', weight: 18.3, category: '9P Sprockets' },
  { name: '24T 9P Sprocket', weight: 27.2, category: '9P Sprockets' },

  { name: '8T 6P Sprocket', weight: 8.5, category: '6P Sprockets' },
  { name: '16T 6P Sprocket', weight: 4.2, category: '6P Sprockets' },

  { name: '10T 3P Sprocket', weight: 0.6, category: '3P Sprockets' },
  { name: '15T 3P Sprocket', weight: 1.1, category: '3P Sprockets' },
  { name: '24T 3P Sprocket', weight: 1.8, category: '3P Sprockets' },
  { name: '40T 3P Sprocket', weight: 5.9, category: '3P Sprockets' },

  { name: 'HS Chain (1x Link)', weight: 0.4, category: 'Chains' },
  { name: 'HS Attachment Chain', weight: 1.5, category: 'Chains' },
  { name: 'Conveyor Chain', weight: 1.3, category: 'Chains' },
  { name: 'Tread Chain', weight: 1.8, category: 'Chains' },
  { name: '6P Chain', weight: 0.2, category: 'Chains' },
  { name: '3P Chain (5x Links)', weight: 0.2, category: 'Chains' },

  { name: 'Inertial Sensor', weight: 8.2, category: 'Sensors' },
  { name: 'Optical Sensor', weight: 9.5, category: 'Sensors' },
  { name: 'Distance Sensor', weight: 9.5, category: 'Sensors' },
  { name: 'Rotational Sensor', weight: 23.3, category: 'Sensors' },
  { name: 'GPS Sensor', weight: 45.3, category: 'Sensors' },

  { name: 'V1 Single Piston', weight: 36.7, category: 'Pneumatics' },
  { name: 'V1 Solenoid Fitting', weight: 1.5, category: 'Pneumatics' },
  { name: 'V1 Piston Fitting', weight: 2.9, category: 'Pneumatics' },
  { name: 'V1 T-Fitting', weight: 2.4, category: 'Pneumatics' },
  { name: 'V2 Air Tank', weight: 308.6, category: 'Pneumatics' },
  { name: '50mm Piston', weight: 34.7, category: 'Pneumatics' },
  { name: '75mm Piston', weight: 40.9, category: 'Pneumatics' },

  { name: 'Steel Washer', weight: 0.3, category: 'Misc.' },
  { name: 'Large Steel Washer', weight: 0.6, category: 'Misc.' },
  { name: '1" Washer', weight: 6.2, category: 'Misc.' },
  { name: '1/2" Coupler', weight: 0.9, category: 'Misc.' },
  { name: '1" Coupler', weight: 1.9, category: 'Misc.' },
  { name: '45° Gusset', weight: 6.2, category: 'Misc.' },
  { name: '90° Gusset', weight: 6.2, category: 'Misc.' },
  { name: '4" Ziptie', weight: 0.2, category: 'Misc.' },
  { name: '11" Ziptie', weight: 1.4, category: 'Misc.' },
  { name: 'Rubber Link', weight: 3.8, category: 'Misc.' },
  { name: 'License Plate', weight: 15.9, category: 'Misc.' },
  { name: 'Rubber Stopper', weight: 5.5, category: 'Misc.' },
  { name: 'LS Collar', weight: 3.7, category: 'Misc.' },
  { name: 'LS Plastic Collar', weight: 0.4, category: 'Misc.' },
  { name: 'Rubber Collar', weight: 1.7, category: 'Misc.' },
  { name: 'LS Metal Lock', weight: 3.4, category: 'Misc.' },
  { name: 'HS Metal Lock', weight: 3.3, category: 'Misc.' },
  { name: 'Pulley Wheel', weight: 3.1, category: 'Misc.' },
  { name: 'Intake Roller', weight: 7.6, category: 'Misc.' },
  { name: 'Rubber Band', weight: 1.1, category: 'Misc.' },
  { name: 'Worm Gear', weight: 2.8, category: 'Misc.' },
  { name: 'V1 Rack Gear', weight: 9.5, category: 'Misc.' },
  { name: 'V2 Rack Gear', weight: 6.3, category: 'Misc.' },
  { name: 'Cutout 60T', weight: 15.4, category: 'Misc.' },
];
